theme: minima

# Add custom stylesheets
sass:
  style: compressed
  load_paths:
    - assets/css

# Optional: Custom baseurl if needed
baseurl: "" # Leave empty for the root or set to a specific path if hosting in a subdirectory

# Optional: Site title and description
title: "Subbareddy Paturu's Knowledge Hub"
description: "Exploring AI, Knowledge Management, and Beyond"
