theme: minima
title: My GitHub Page
description: "Welcome to my personal GitHub Page!"

# Add custom styles
stylesheet: /assets/css/styles.scss


navigation:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/
